version: '3'
services:
  db:
    image: mysql:latest
    ports:
        - '3306:3306'
    environment:
        MYSQL_ROOT_PASSWORD: mysecret
        MYSQL_DATABASE: mydatabase
        MYSQL_USER: user
        MYSQL_PASSWORD: mypassword
